### ISSUE TITLE
Jailbreak 14 Todo List

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Spesships/Jailbreak-14#1]
Every good fork requires a good to-do list.

# Game
## Jobs
- [ ] Remove all the jobs except for doctors, Captain, CMO, HoS (directs the security), Warden (directs the security & hos), Security Officer, Security Cadet and Prisoner
- [ ] Make Prisoner a roundstart role
- [ ] Paramedics
- [ ] ERT + subclasses (e.g; crowd control team, structural response team, biological response team)

## Maps
- [ ] Prison Station

# Server
- [x] PostgresSQL
- [ ] Suitable Server Host
- [ ] CDN (optional)
